apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: dev 
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
    nodePort: 30171


